import type { RequestOptions } from '../client.js';
import type { Page } from '../pagination.js';
import { APIResource } from './base.js';

/** Promotion types used by the link-based referral system. */
export type ReferralPromoType =
  | 'first_time_value_off'
  | 'first_time_percent_off'
  | 'always_value_off'
  | 'always_percent_off';

/** Promotion types used by referral channels / coupon codes (a distinct vocabulary). */
export type CouponPromoType = 'percent_off' | 'value_off';

/** The referral config singleton. */
export interface ReferralConfig {
  /** Unique identifier of the referral config instance. Should not change for the user. */
  id: number;
  /** `payout` mode sends earn-outs to PayPal; `credits` converts them to account credits. */
  mode: 'payout' | 'credits';
  /** May be null if mode is `credits`; must be set if mode is `payout`. */
  paypal_payout_email: string | null;
  /** Whether ID verification is required (once payout conditions are met). */
  id_verification_required: boolean;
  /** USD earned, pending conversion to account credits at the next earn-out. */
  credits_earned: number;
  /** USD earned, pending payout to PayPal at the next earn-out. */
  payouts_earned: number;
  /** Total amount of credits earned so far. */
  total_credits_earned: number;
  /** Total amount of payouts earned so far. */
  total_payouts_earned: number;
  /** Number of unique users referred. */
  number_of_users_referred: number;
  /** Number of unique users who upgraded. */
  number_of_users_upgraded: number;
  /** Frequency of earn-outs, in `[DD] [HH:MM:SS]` format. */
  earn_out_frequency: string;
  /** Timestamp of the next earn-out. */
  next_earn_out_date: string;
  /** Minimum USD needed for the earn-out to be processed. */
  minimum_earn_out_amount: number;
  /** Unique referral code of this user. */
  referral_code: string;
  /** Example referral URL to the Webshare home page. */
  referral_url: string;
  /** Maximum credits/payouts that can be earned from a single referral. */
  referral_maximum_credits: number;
  /** Ratio of credits/payouts earned from a referral purchase (e.g. 0.25). */
  referral_credit_ratio: number;
  /** Grace period before a referral credit/payout becomes available (Django duration string). */
  referral_payment_pending_days: string;
  /** The type of promotion referrals will receive. May be null. */
  promo_type: ReferralPromoType | null;
  /** The value of the promotion (10 or 20). Null if `promo_type` is null. */
  promo_value: number | null;
  created_at: string;
  updated_at: string;
}

export interface ReferralConfigUpdateParams {
  /** The only writable fields are `mode` and `paypal_payout_email`. */
  mode?: 'payout' | 'credits';
  /** Must be set if the mode is `payout`. */
  paypal_payout_email?: string | null;
}

/** The coupon code applied to the user. All fields are null when no code is applied. */
export interface CouponCode {
  code: string | null;
  promo_type: CouponPromoType | null;
  /** Decimal serialized as string; e.g. `"0.20"` for 20% off, or an absolute USD amount. */
  promo_value: string | null;
  /** Human-readable description; may be an empty string. */
  description: string | null;
  /** If true, the discount applies to every renewal; if false, only to the first purchase. */
  is_recurring: boolean | null;
}

export interface CouponCodeApplyParams {
  /**
   * The coupon code to apply (max 100 characters; case-insensitive, trimmed).
   * Documented 400 error codes: `not_found`, `code_inactive`, `code_expired`,
   * `self_referral`, `already_redeemed`.
   */
  code: string;
}

/** A referral channel (a coupon code owned by the user; created by the Webshare team). */
export interface ReferralChannel {
  /** Unique identifier of the referral channel. */
  id: number;
  /** The coupon code other users apply to receive the discount. */
  code: string;
  /** Human-readable description; may be an empty string. */
  description: string;
  promo_type: CouponPromoType;
  /** Decimal serialized as string. */
  promo_value: string;
  /** If false, the code can no longer be applied by new users. */
  is_active: boolean;
  /** If true, the discount applies to every renewal of the redeemer's plan. */
  is_recurring: boolean;
  /** Timestamp from which the code becomes applicable. */
  start_date: string;
  /** Timestamp after which the code can no longer be applied. May be null. */
  end_date: string | null;
  /** Total distinct redemptions of this channel across all users. */
  total_uses: number;
  /** Total USD commission earned through this channel. */
  total_commission: number;
  /** Total USD revenue generated by redeemers of this channel. */
  total_revenue: number;
  /** Commission rate (0-1, decimal as string) during the initial period. */
  initial_rate: string;
  /** Commission rate (0-1, decimal as string) after the initial period. */
  ongoing_rate: string;
  /** Length, in days, of the initial commission period. */
  initial_rate_period_days: number;
  /** Maximum USD commission (decimal as string) from a single referred user. */
  max_earnings_per_referred: string;
  created_at: string;
}

/** A referral credit earned when a referral spends money on Webshare. */
export interface ReferralCredit {
  /** Unique identifier of the referral credit instance. */
  id: number;
  /** Unique identifier of the referred user who spent money on Webshare. */
  user_id: number;
  /** Whether the credit is in payout or credits mode. Cannot be changed. */
  mode: string;
  /** Amount earned in USD. */
  amount: number;
  /** Becomes `available` after `referral_payment_pending_days`. */
  status: 'pending' | 'available' | 'reverted';
  /** ID of the referral channel that produced this credit. Null for link-based referrals. */
  referral_channel: number | null;
  /** Code of the referral channel that produced this credit. Null for link-based referrals. */
  referral_channel_code: string | null;
  created_at: string;
  updated_at: string;
  /** When this credit was reverted. Null unless the status is `reverted`. */
  reverted_at: string | null;
}

export interface ReferralCreditListParams {
  /** Page number. */
  page?: number;
  /** Number of results per page. */
  page_size?: number;
  /** Filter by payout or credits. */
  mode?: 'payout' | 'credits';
  /** Filter by status. */
  status?: 'pending' | 'available' | 'reverted';
  /** Filter by the ID of a referral channel you own. */
  referral_channel?: number;
  /** Ordering fields: `id`, `mode`, `amount`, `status`, `created_at`, `updated_at`, `reverted_at`; prefix `-` for descending. */
  ordering?: string;
}

/** An earn-out: a batch conversion of pending balance into credits or a PayPal payout. */
export interface ReferralEarnout {
  /** Unique identifier of the earn out instance. */
  id: number;
  /** Whether the earn out is a payout or credits. */
  mode: string;
  /** If mode is payout, the PayPal email which received the funds. May be null. */
  paypal_payout_email: string | null;
  /** Amount earned out in USD. */
  amount: number;
  status: 'processing' | 'completed' | 'failed';
  /** If status is `failed`, the error; otherwise null. */
  error_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface ReferralEarnoutListParams {
  /** Page number. */
  page?: number;
  /** Number of results per page. */
  page_size?: number;
}

export interface ReferralCodeInfoParams {
  /** The referral code to look up. */
  referral_code: string;
}

/** Publicly available information about a referral code. */
export interface ReferralCodeInfo {
  referral_code: string;
  /** The type of promotion. May be null. */
  promo_type: ReferralPromoType | null;
  /** The value of the promotion (10 or 20). Null if `promo_type` is null. */
  promo_value: number | null;
}

export class Referral extends APIResource {
  /** Retrieves the referral config (switching to the affiliate program via the API indicates consent to the affiliate agreement). */
  getConfig(options?: RequestOptions): Promise<ReferralConfig> {
    return this._client.request({ method: 'GET', path: '/api/v2/referral/config/' }, options);
  }

  /** Updates the referral config. Only `mode` and `paypal_payout_email` are writable. */
  updateConfig(params: ReferralConfigUpdateParams, options?: RequestOptions): Promise<ReferralConfig> {
    return this._client.request({ method: 'PATCH', path: '/api/v2/referral/config/', body: params }, options);
  }

  /** Retrieves the coupon code currently applied to the user (all fields null when none). */
  getCouponCode(options?: RequestOptions): Promise<CouponCode> {
    return this._client.request({ method: 'GET', path: '/api/v2/referral/coupon-code/' }, options);
  }

  /**
   * Applies a coupon code (replacing any currently applied one). Has its own
   * rate limit of 5 requests per minute per user.
   */
  applyCouponCode(params: CouponCodeApplyParams, options?: RequestOptions): Promise<CouponCode> {
    return this._client.request({ method: 'POST', path: '/api/v2/referral/coupon-code/', body: params }, options);
  }

  /** Removes the applied coupon code. Already-redeemed codes are not affected. */
  removeCouponCode(options?: RequestOptions): Promise<void> {
    return this._client.request(
      { method: 'DELETE', path: '/api/v2/referral/coupon-code/', responseType: 'void' },
      options,
    );
  }

  /** Lists the referral channels owned by the user. NOT paginated — returns a bare array ordered by id ascending. */
  listChannels(options?: RequestOptions): Promise<ReferralChannel[]> {
    return this._client.request({ method: 'GET', path: '/api/v2/referral/channel/' }, options);
  }

  /** Lists referral credits in paginated format. */
  listCredits(params?: ReferralCreditListParams, options?: RequestOptions): Promise<Page<ReferralCredit>> {
    return this._client.requestPage('/api/v2/referral/credit/', { ...params }, options);
  }

  /** Retrieves a referral credit. */
  getCredit(id: number, options?: RequestOptions): Promise<ReferralCredit> {
    return this._client.request({ method: 'GET', path: `/api/v2/referral/credit/${id}/` }, options);
  }

  /** Lists earn outs in paginated format. (Note: the docs show this path without a trailing slash.) */
  listEarnouts(params?: ReferralEarnoutListParams, options?: RequestOptions): Promise<Page<ReferralEarnout>> {
    return this._client.requestPage('/api/v2/referral/earnout', { ...params }, options);
  }

  /** Retrieves an earn out. */
  getEarnout(id: number, options?: RequestOptions): Promise<ReferralEarnout> {
    return this._client.request({ method: 'GET', path: `/api/v2/referral/earnout/${id}/` }, options);
  }

  /** Retrieves the publicly available information of a referral code. Unauthenticated. */
  getCodeInfo(params: ReferralCodeInfoParams, options?: RequestOptions): Promise<ReferralCodeInfo> {
    return this._client.request(
      { method: 'GET', path: '/api/v2/referral/code/info/', query: { ...params }, auth: false },
      options,
    );
  }
}
