import type { RequestOptions } from '../client.js';
import { APIResource } from './base.js';

/** A two-factor authentication method. */
export interface TwoFactorAuthMethod {
  /** Unique identifier of the 2FA method instance. */
  id: number;
  /** The type of 2FA method. */
  type: 'email_code' | 'device_totp';
  /** Whether this is the active 2FA method (each account has exactly one). */
  active: boolean;
  /**
   * Hex formatted secret key for the TOTP device. Only present right after
   * creating a `device_totp` method; otherwise hidden. Surface it
   * immediately — it is never shown again.
   */
  secret_key?: string;
  created_at: string;
  updated_at: string;
}

export interface ChangeTwoFactorMethodParams {
  /** The type of 2FA method. Email activates instantly; `device_totp` requires activation. */
  type?: 'email_code' | 'device_totp';
}

export interface ActivateTwoFactorMethodParams {
  /** Code generated by the 2FA device. */
  code_1?: string;
  /** A second, different code generated by the 2FA device. */
  code_2?: string;
}

export interface SubmitTwoFactorCodeParams {
  /** Code received in the email or generated by the TOTP device. */
  code?: string;
  /** The recaptcha token (can be invisible recaptcha). */
  recaptcha?: string;
}

export interface ResendTwoFactorEmailResponse {
  email_sent: boolean;
}

export class TwoFactorAuth extends APIResource {
  /** Returns the active 2FA method for the account (email 2FA is on by default). */
  getMethod(options?: RequestOptions): Promise<TwoFactorAuthMethod> {
    return this._client.request({ method: 'GET', path: '/api/v2/twofactorauth/method/current/' }, options);
  }

  /**
   * Changes the default 2FA method. When creating a `device_totp` method, the
   * response includes `secret_key` — shown only in this response.
   */
  changeMethod(params: ChangeTwoFactorMethodParams, options?: RequestOptions): Promise<TwoFactorAuthMethod> {
    return this._client.request({ method: 'POST', path: '/api/v2/twofactorauth/method/', body: params }, options);
  }

  /**
   * Activates a device (TOTP) 2FA method with two consecutive codes
   * (`code_1` and `code_2` cannot be the same).
   */
  activateMethod(
    id: number,
    params: ActivateTwoFactorMethodParams,
    options?: RequestOptions,
  ): Promise<TwoFactorAuthMethod> {
    return this._client.request(
      { method: 'POST', path: `/api/v2/twofactorauth/method/${id}/activate/`, body: params },
      options,
    );
  }

  /**
   * Enters the 2FA code after receiving a 403 with code `2fa_needed`; the
   * previously failed request can then be replayed. 2FA only applies to login
   * tokens, never to API keys.
   */
  submitCode(params: SubmitTwoFactorCodeParams, options?: RequestOptions): Promise<void> {
    return this._client.request(
      { method: 'POST', path: '/api/v2/twofactorauth/codeauth/', body: params, responseType: 'void' },
      options,
    );
  }

  /** Resends the 2FA code via email (email 2FA method only). */
  resendEmailCode(options?: RequestOptions): Promise<ResendTwoFactorEmailResponse> {
    return this._client.request({ method: 'POST', path: '/api/v2/twofactorauth/email/resend/' }, options);
  }
}
